feat: final production deployment and monitoring

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -15,6 +15,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       DEPLOY_SHA: ${{ github.event.workflow_run.head_sha }}
+      APP_DOMAIN: ${{ vars.APP_DOMAIN }}
 
     steps:
       - name: Prepare SSH
@@ -39,8 +40,98 @@ jobs:
         run: |
           ssh "$SERVER_USER@$SERVER_HOST" "
             DEPLOY_SHA='$DEPLOY_SHA'
+            APP_DOMAIN='$APP_DOMAIN'
             IMAGE_TAG="\$DEPLOY_SHA"
 
+            check_production(){
+              echo "Check API health"
+              API_SUCCESS=false
+              for i in {1..12}; do
+                status=\$(sudo docker inspect --format="{{.State.Health.Status}}" backend-api)
+      
+                echo "API health status: \$status"
+
+                if [ "\$status" = "healthy" ]; then
+                  API_SUCCESS=true
+                  break
+                fi
+                sleep 5
+              done
+              if [ "\$API_SUCCESS" != "true" ]; then
+                echo "API health check failed"
+                return 1
+              fi
+
+              WORKER_ID=\$(sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml ps -q worker)
+              PUBLISHER_ID=\$(sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml ps -q publisher)
+              
+              if [ -z "\$WORKER_ID" ] || [ -z "\$PUBLISHER_ID" ];then
+                echo "Worker or Publisher container not found"
+                return 1
+              fi              
+              WORKER_RUNNING=\$(sudo docker inspect --format="{{.State.Running}}" "\$WORKER_ID")
+              PUBLISHER_RUNNING=\$(sudo docker inspect --format="{{.State.Running}}" "\$PUBLISHER_ID")
+                  
+              echo "Worker running: \$WORKER_RUNNING"
+              echo "Publisher running: \$PUBLISHER_RUNNING"
+              if [ "\$WORKER_RUNNING" != "true" ] || [ "\$PUBLISHER_RUNNING" != "true" ]; then
+                return 1 
+              fi
+              
+              echo "Check Nginx config"
+              if ! sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml exec -T web nginx -t;then
+                echo "Nginx config check failed"
+                return 1
+              fi
+              echo "Reloading Nginx"
+              if ! sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml exec -T web nginx -s reload;then  
+                echo "Nginx reload failed"
+                return 1
+              fi
+              echo "Check HTTPS endpoint"
+              if ! curl -fsS "https://\$APP_DOMAIN/health" > /dev/null;then
+                echo "HTTPS smoke test failed"
+                return 1
+              fi
+              echo "Check Prometheus Config"
+              if ! sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml exec -T prometheus promtool check config /etc/prometheus/prometheus.yml;then
+                echo "Prometheus config check failed"
+                return 1
+              fi
+              echo "Reloading Prometheus"
+              if ! curl -f -X POST http://127.0.0.1:9090/-/reload; then
+                echo "Prometheus reload failed"
+                return 1
+              fi
+              echo "Check Prometheus targets"
+              if ! python3 scripts/check_monitoring.py; then
+                echo "Prometheus scrape failed"
+                return 1
+              fi
+              echo "Check Grafana health"
+              GRAFANA_SUCCESS=false
+
+              for i in {1..6}; do
+                if curl -fsS http://127.0.0.1:3000/api/health > /dev/null; then
+                  GRAFANA_SUCCESS=true
+                  break
+                fi
+
+                echo "Grafana not ready, retrying..."
+                sleep 5
+              done
+
+              if [ "\$GRAFANA_SUCCESS" != "true" ]; then
+                echo "Grafana health check failed"
+                return 1
+              fi
+              echo "Production check passed"
+              return 0
+            }
+
+
+            
+            
             cd ~/backend-portfolio || exit 1
 
             DISK_USAGE=\$(df -P / | awk 'NR==2 {print \$5}' | tr -d '%')
@@ -71,73 +162,77 @@ jobs:
 
             git fetch origin || exit 1
             git reset --hard "\$DEPLOY_SHA" || exit 1
-
-            sudo docker run --rm --network backend-portfolio_default -v "./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro" -v "/etc/letsencrypt:/etc/letsencrypt:ro" nginx nginx -t || exit 1
-            sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml build api || exit 1
-            sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml run --rm api alembic upgrade head || exit 1
-            sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml up -d api || exit 1
             
-            DEPLOY_SUCCESS=false
-            for i in {1..12}; do
-              status=\$(sudo docker inspect --format="{{.State.Health.Status}}" backend-api)
-
-              echo "API health status: \$status"
-
-              if [ "\$status" = "healthy" ]; then
-                DEPLOY_SUCCESS=true
-                break
-              fi
-
-              sleep 5
-            done
-
-            if [ "\$DEPLOY_SUCCESS" = "true" ]; then
-              echo "API deployment successful"
-              sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml up -d --no-deps web || exit 1
-              sudo docker exec backend-portfolio-web-1 nginx -t || exit 1
-              sudo docker exec backend-portfolio-web-1 nginx -s reload || exit 1
-              echo "Deployment successful"
-              DEPLOY_IMAGE="backend-portfolio-api:\$DEPLOY_SHA"
-
-              for image in \$(sudo docker image ls "backend-portfolio-api:*" --format "{{.Repository}}:{{.Tag}}"); do
-                if [ "\$image" = "\$DEPLOY_IMAGE" ] || [ "\$image" = "\$CURRENT_IMAGE" ]; then
-                  echo "keep:\$image"
-                else
-                  sudo docker image rm "\$image"
-                  echo "delete:\$image"
-                fi
-              done
-              
-              exit 0
-            else 
-              echo "Deployment failed , starting rollback"
+            PREPARE_SUCCESS=true
+            if ! sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml build api; then
+              echo "API image build failed"
+              PREPARE_SUCCESS=false
             fi
+            if [ "\$PREPARE_SUCCESS" = "true" ]; then
+              if ! sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml up -d --wait db redis; then
+                echo "DB or Redis running failed"
+                PREPARE_SUCCESS=false
+              fi
+            fi
+            
+            if [ "\$PREPARE_SUCCESS" = "true" ]; then
+              if ! sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml run --rm api alembic upgrade head; then
+                echo "DB alembic upgrade failed"
+                PREPARE_SUCCESS=false
+              fi
+            fi  
+            
+            if [ "\$PREPARE_SUCCESS" = "true" ]; then
+              if ! sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml up -d;then
+                echo "Production compose up failed"
+                PREPARE_SUCCESS=false
+              fi
+            fi
+            
+            if [ "\$PREPARE_SUCCESS" = "true" ]; then
+              if check_production; then
+                echo "Deployment successful"
+                DEPLOY_IMAGE="backend-portfolio-api:\$DEPLOY_SHA"
 
+                for image in \$(sudo docker image ls "backend-portfolio-api:*" --format "{{.Repository}}:{{.Tag}}"); do
+                  if [ "\$image" = "\$DEPLOY_IMAGE" ] || [ "\$image" = "\$CURRENT_IMAGE" ]; then
+                    echo "keep:\$image"
+                  else
+                    sudo docker image rm "\$image"
+                    echo "delete:\$image"
+                  fi
+                done
+                exit 0
+              fi
+            fi
+            
+            echo "Deployment failed, starting rollback"
             if [ "\$CAN_ROLLBACK" = "false" ]; then
               echo "Cannot rollback,no useful image"
               exit 1
             else 
               echo "Rollback processing"
-              sudo IMAGE_TAG="\$CURRENT_TAG" docker compose -f compose.yaml -f compose.prod.yaml up -d api || exit 1
+              git reset --hard "\$CURRENT_TAG" || exit 1
             fi
             
-            ROLLBACK_SUCCESS=false
-            for i in {1..12}; do 
-              status=\$(sudo docker inspect backend-api --format "{{.State.Health.Status}}")
-
-              if [ "\$status" = "healthy" ]; then
-                ROLLBACK_SUCCESS=true
-                break
-              fi
-
-              sleep 5
-            done
-
-            if [ "\$ROLLBACK_SUCCESS" = "true" ]; then
-              echo "Rollback successful"
+            IMAGE_TAG="\$CURRENT_TAG"
+            if ! sudo IMAGE_TAG="\$IMAGE_TAG" docker compose -f compose.yaml -f compose.prod.yaml up -d; then
+              echo "Rollback compose up failed"
               exit 1
+            fi
+
+            if check_production; then
+              echo "Rollback successful"
+              FAILED_IMAGE="backend-portfolio-api:\$DEPLOY_SHA"
+              if sudo docker image rm "\$FAILED_IMAGE"; then
+                echo "Deleted failed deployment image: \$FAILED_IMAGE"
+              else
+                echo "Could not delete failed deployment image: \$FAILED_IMAGE"
+              fi
             else
               echo "Rollback failed"
-              exit 1  
-            fi  
-            "
+            fi
+            exit 1
+
+
+
